package com.oz.test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-05-21T12:54:17.390+08:00
 * Generated source version: 3.1.0
 * 
 */
@WebServiceClient(name = "CustomerServiceImplService", 
                  wsdlLocation = "http://localhost:8088/MOVIE_CXF/services/customerSerevice?wsdl",
                  targetNamespace = "http://webservice.ssh_cxf.com/") 
public class CustomerServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.ssh_cxf.com/", "CustomerServiceImplService");
    public final static QName CustomerServiceImplPort = new QName("http://webservice.ssh_cxf.com/", "CustomerServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8088/MOVIE_CXF/services/customerSerevice?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CustomerServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8088/MOVIE_CXF/services/customerSerevice?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CustomerServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CustomerServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    public CustomerServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }    




    /**
     *
     * @return
     *     returns CustomerService
     */
    @WebEndpoint(name = "CustomerServiceImplPort")
    public CustomerService getCustomerServiceImplPort() {
        return super.getPort(CustomerServiceImplPort, CustomerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerService
     */
    @WebEndpoint(name = "CustomerServiceImplPort")
    public CustomerService getCustomerServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CustomerServiceImplPort, CustomerService.class, features);
    }

}
