
package com.oz.test;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-05-21T12:54:17.344+08:00
 * Generated source version: 3.1.0
 * 
 */
public final class CustomerService_CustomerServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.ssh_cxf.com/", "CustomerServiceImplService");

    private CustomerService_CustomerServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CustomerServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CustomerServiceImplService ss = new CustomerServiceImplService(wsdlURL, SERVICE_NAME);
        CustomerService port = ss.getCustomerServiceImplPort();  
        
        {
        System.out.println("Invoking operationService...");
        java.lang.String _operationService_arg0 = "";
        java.lang.String _operationService__return = port.operationService(_operationService_arg0);
        System.out.println("operationService.result=" + _operationService__return);


        }

        System.exit(0);
    }

}
