
package com.oz.test;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-05-21T12:54:17.390+08:00
 * Generated source version: 3.1.0
 * 
 */
 
public class CustomerService_CustomerServiceImplPort_Server{

    protected CustomerService_CustomerServiceImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new CustomerServiceImplPortImpl();
        String address = "http://localhost:8088/MOVIE_CXF/services/customerSerevice";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new CustomerService_CustomerServiceImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
