
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.oz.test;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-05-21T12:54:17.375+08:00
 * Generated source version: 3.1.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "CustomerServiceImplService",
                      portName = "CustomerServiceImplPort",
                      targetNamespace = "http://webservice.ssh_cxf.com/",
                      wsdlLocation = "http://localhost:8088/MOVIE_CXF/services/customerSerevice?wsdl",
                      endpointInterface = "com.zzzl.webservice.qidian.CustomerService")
                      
public class CustomerServiceImplPortImpl implements CustomerService {

    private static final Logger LOG = Logger.getLogger(CustomerServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.zzzl.webservice.qidian.CustomerService#operationService(java.lang.String  arg0 )*
     */
    public java.lang.String operationService(java.lang.String arg0) { 
        LOG.info("Executing operation operationService");
        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
